if(EXISTS "/Users/bryce/Documents/GitHub/faiss/build-mps-py/faiss/gpu/test/TestMpsIndexFlat[1]_tests.cmake")
  include("/Users/bryce/Documents/GitHub/faiss/build-mps-py/faiss/gpu/test/TestMpsIndexFlat[1]_tests.cmake")
else()
  add_test(TestMpsIndexFlat_NOT_BUILT TestMpsIndexFlat_NOT_BUILT)
endif()
